Repository Nova-Storage/starca, pull requests merged in 2022-11, with the labels that each got.

#26 Readme networking
  README.md
Labels: documentation

#27 Updated Readme - Added more networking example code snippets
  .idea/gradle.xml
  .idea/misc.xml
  README.md
Labels: documentation

#30 Activities layouts
  .idea/misc.xml
  README.md
  app/src/debug/res/drawable-anydpi/ic_conversations.xml
  app/src/debug/res/drawable-anydpi/ic_create.xml
  app/src/debug/res/drawable-anydpi/ic_dashboard.xml
  app/src/debug/res/drawable-anydpi/ic_logout.xml
  app/src/debug/res/drawable-anydpi/ic_profile.xml
  app/src/debug/res/drawable-hdpi/ic_conversations.png
  app/src/debug/res/drawable-hdpi/ic_create.png
  app/src/debug/res/drawable-hdpi/ic_dashboard.png
  app/src/debug/res/drawable-hdpi/ic_logout.png
  app/src/debug/res/drawable-hdpi/ic_profile.png
  app/src/debug/res/drawable-mdpi/ic_conversations.png
  app/src/debug/res/drawable-mdpi/ic_create.png
  app/src/debug/res/drawable-mdpi/ic_dashboard.png
  app/src/debug/res/drawable-mdpi/ic_logout.png
  app/src/debug/res/drawable-mdpi/ic_profile.png
  app/src/debug/res/drawable-xhdpi/ic_conversations.png
  app/src/debug/res/drawable-xhdpi/ic_create.png
  app/src/debug/res/drawable-xhdpi/ic_dashboard.png
  app/src/debug/res/drawable-xhdpi/ic_logout.png
  app/src/debug/res/drawable-xhdpi/ic_profile.png
  app/src/debug/res/drawable-xxhdpi/ic_conversations.png
  app/src/debug/res/drawable-xxhdpi/ic_create.png
  app/src/debug/res/drawable-xxhdpi/ic_dashboard.png
  app/src/debug/res/drawable-xxhdpi/ic_logout.png
  app/src/debug/res/drawable-xxhdpi/ic_profile.png
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/starca/LoginActivity.kt
  app/src/main/java/com/example/starca/MainActivity.kt
  app/src/main/java/com/example/starca/fragments/ConversationsFragment.kt
  app/src/main/java/com/example/starca/fragments/CreateListingDetailsFragment.kt
  app/src/main/java/com/example/starca/fragments/CreateListingImageFragment.kt
  app/src/main/java/com/example/starca/fragments/CreateListingSubmitFragment.kt
  app/src/main/java/com/example/starca/fragments/DashboardFragment.kt
  app/src/main/java/com/example/starca/fragments/ProfileFragment.kt
  app/src/main/java/com/example/starca/fragments/SettingsFragment.kt
  app/src/main/res/drawable/starca_logo.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_conversations.xml
  app/src/main/res/layout/fragment_create_listing_details.xml
  app/src/main/res/layout/fragment_create_listing_image.xml
  app/src/main/res/layout/fragment_create_listing_submit.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/menu/menu_bottom_navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: documentation, enhancement

#31 Sign-in and register fragments
  .gitignore
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/starca/LoginActivity.kt
  app/src/main/java/com/example/starca/MainActivity.kt
  app/src/main/java/com/example/starca/StarcaApplication.kt
  app/src/main/java/com/example/starca/fragments/CreateListingDetailsFragment.kt
  app/src/main/java/com/example/starca/fragments/CreateListingImageFragment.kt
  app/src/main/java/com/example/starca/fragments/CreateListingSubmitFragment.kt
  app/src/main/java/com/example/starca/fragments/RegisterFragment.kt
  app/src/main/java/com/example/starca/fragments/SignInFragment.kt
  app/src/main/java/com/example/starca/models/User.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_create_listing_details.xml
  app/src/main/res/layout/fragment_create_listing_image.xml
  app/src/main/res/layout/fragment_create_listing_submit.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/menu/menu_login_bottom_navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  settings.gradle
Labels: enhancement

#32 Email verification is now required. User is prompted to verify after …
  app/src/main/java/com/example/starca/StarcaApplication.kt
  app/src/main/java/com/example/starca/fragments/RegisterFragment.kt
  app/src/main/java/com/example/starca/fragments/SignInFragment.kt
  app/src/main/java/com/example/starca/models/Listing.kt
  app/src/main/java/com/example/starca/models/User.kt
Labels: enhancement

#33 Implemented Dashboard basic functionality + Google Maps
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/starca/fragments/DashboardFragment.kt
  app/src/main/java/com/example/starca/fragments/ListingsAdapter.kt
  app/src/main/java/com/example/starca/fragments/MapsFragment.kt
  app/src/main/res/drawable/rounded_corners.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_maps.xml
  app/src/main/res/layout/item_listing.xml
  build.gradle
Labels: enhancement

#34 Stable maps
  app/src/main/java/com/example/starca/fragments/CreateListingDetailsFragment.kt
  app/src/main/java/com/example/starca/fragments/DashboardFragment.kt
  app/src/main/java/com/example/starca/fragments/MapsFragment.kt
  app/src/main/java/com/example/starca/models/Listing.kt
Labels: enhancement

#35 Sprint1 andrew sakar changes
  .idea/gradle.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/starca/MainActivity.kt
  app/src/main/java/com/example/starca/fragments/CreateListingDetailsFragment.kt
  app/src/main/java/com/example/starca/fragments/CreateListingImageFragment.kt
  app/src/main/java/com/example/starca/fragments/CreateListingSubmitFragment.kt
  app/src/main/java/com/example/starca/models/Listing.kt
  app/src/main/res/drawable/imagepreview.jpg
  app/src/main/res/drawable/rounded_corner.xml
  app/src/main/res/drawable/rounded_edittext.xml
  app/src/main/res/layout/fragment_create_listing_details.xml
  app/src/main/res/layout/fragment_create_listing_image.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/fileprovider.xml
Labels: enhancement

#37 Login UI
  README.md
  app/src/debug/res/drawable-anydpi/ic_badge.xml
  app/src/debug/res/drawable-anydpi/ic_email.xml
  app/src/debug/res/drawable-anydpi/ic_lock.xml
  app/src/debug/res/drawable-anydpi/ic_login_profile.xml
  app/src/debug/res/drawable-hdpi/ic_badge.png
  app/src/debug/res/drawable-hdpi/ic_email.png
  app/src/debug/res/drawable-hdpi/ic_lock.png
  app/src/debug/res/drawable-hdpi/ic_login_profile.png
  app/src/debug/res/drawable-mdpi/ic_badge.png
  app/src/debug/res/drawable-mdpi/ic_email.png
  app/src/debug/res/drawable-mdpi/ic_lock.png
  app/src/debug/res/drawable-mdpi/ic_login_profile.png
  app/src/debug/res/drawable-xhdpi/ic_badge.png
  app/src/debug/res/drawable-xhdpi/ic_email.png
  app/src/debug/res/drawable-xhdpi/ic_lock.png
  app/src/debug/res/drawable-xhdpi/ic_login_profile.png
  app/src/debug/res/drawable-xxhdpi/ic_badge.png
  app/src/debug/res/drawable-xxhdpi/ic_email.png
  app/src/debug/res/drawable-xxhdpi/ic_lock.png
  app/src/debug/res/drawable-xxhdpi/ic_login_profile.png
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/starca/LoginActivity.kt
  app/src/main/java/com/example/starca/fragments/RegisterFragment.kt
  app/src/main/java/com/example/starca/fragments/SignInFragment.kt
  app/src/main/res/drawable/background_image.jpg
  app/src/main/res/drawable/starca_logo_icon.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#38 Maps Search update.
  .idea/gradle.xml
  app/build.gradle
  app/src/debug/res/drawable-hdpi/ic_search_starca.png
  app/src/debug/res/drawable-mdpi/ic_search_starca.png
  app/src/debug/res/drawable-xhdpi/ic_search_starca.png
  app/src/debug/res/drawable-xxhdpi/ic_search_starca.png
  app/src/debug/res/drawable-xxxhdpi/ic_search_starca.png
  app/src/main/java/com/example/starca/fragments/DashboardFragment.kt
  app/src/main/java/com/example/starca/fragments/MapsFragment.kt
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/search_item.xml
Labels: enhancement

#39 bug: fix text overlapping each other when user filling out listing form
  app/src/main/java/com/example/starca/fragments/CreateListingDetailsFragment.kt
  app/src/main/res/layout/fragment_create_listing_details.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#41 Settings page dev
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/starca/SettingsActivity.kt
  app/src/main/java/com/example/starca/StarcaApplication.kt
  app/src/main/java/com/example/starca/fragments/EditEmailFragment.kt
  app/src/main/java/com/example/starca/fragments/EditPasswordFragment.kt
  app/src/main/java/com/example/starca/fragments/EditUsernameFragment.kt
  app/src/main/java/com/example/starca/fragments/ProfileFragment.kt
  app/src/main/java/com/example/starca/fragments/SettingsFragment.kt
  app/src/main/java/com/example/starca/models/Image.kt
  app/src/main/res/drawable/edit_profile_picture_icon.xml
  app/src/main/res/drawable/ic_outline_add_a_photo_30.xml
  app/src/main/res/drawable/ic_outline_settings_24.xml
  app/src/main/res/drawable/rounded_buttons.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/fragment_edit_email.xml
  app/src/main/res/layout/fragment_edit_password.xml
  app/src/main/res/layout/fragment_edit_username.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, Story

#45 Readme stories
  README.md
Labels: documentation

#47 Profile page
  app/src/debug/res/drawable-anydpi/ic_conversations.xml
  app/src/debug/res/drawable-anydpi/ic_create.xml
  app/src/debug/res/drawable-anydpi/ic_dashboard.xml
  app/src/debug/res/drawable-anydpi/ic_logout.xml
  app/src/debug/res/drawable-anydpi/ic_profile.xml
  app/src/main/java/com/example/starca/MainActivity.kt
  app/src/main/java/com/example/starca/SettingsActivity.kt
  app/src/main/java/com/example/starca/adapters/ListingsGridAdapter.kt
  app/src/main/java/com/example/starca/fragments/ProfileFragment.kt
  app/src/main/java/com/example/starca/fragments/SignInFragment.kt
  app/src/main/java/com/example/starca/models/Listing.kt
  app/src/main/res/drawable/ic_outline_settings_24.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_listing_gridview.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#49 Update profile picture on backend, change password bug fix
  app/build.gradle
  app/src/main/java/com/example/starca/FileUtils.kt
  app/src/main/java/com/example/starca/SettingsActivity.kt
  app/src/main/java/com/example/starca/fragments/EditPasswordFragment.kt
Labels: enhancement

#52 Fix account becomes unverified bug
  app/src/main/java/com/example/starca/SettingsActivity.kt
Labels: bug, enhancement

#54 Detail fragment
  README.md
  app/build.gradle
  app/src/debug/res/drawable-anydpi/ic_logout.xml
  app/src/main/java/com/example/starca/DetailFragment.kt
  app/src/main/java/com/example/starca/ListingRequest.kt
  app/src/main/java/com/example/starca/fragments/CreateListingDetailsFragment.kt
  app/src/main/java/com/example/starca/fragments/CreateListingSubmitFragment.kt
  app/src/main/java/com/example/starca/fragments/ListingsAdapter.kt
  app/src/main/java/com/example/starca/fragments/ProfileFragment.kt
  app/src/main/java/com/example/starca/models/Listing.kt
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/transition/shared_image.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement
