Repository Nova-Storage/starca, pull requests merged in 2022-12, with the labels that each got.

#55 Christian and sakar sprint2 chat
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/starca/DetailFragment.kt
  app/src/main/java/com/example/starca/StarcaApplication.kt
  app/src/main/java/com/example/starca/adapters/ConversationsAdapter.kt
  app/src/main/java/com/example/starca/fragments/ConversationsFragment.kt
  app/src/main/java/com/example/starca/fragments/MessagingFragment.kt
  app/src/main/java/com/example/starca/models/Conversation.kt
  app/src/main/java/com/example/starca/models/Message.kt
  app/src/main/res/layout/fragment_conversations.xml
  app/src/main/res/layout/fragment_messaging.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/item_conversation.xml
Labels: enhancement

#57 Updated README. Added sprint2 gif
  README.md
  sprintgifs/StarcaSprint2.gif
Labels: documentation

#59 You can now remove listing requests.
  app/src/main/java/com/example/starca/DetailFragment.kt
  app/src/main/res/layout/fragment_detail.xml
Labels: enhancement

#60 Newbranch
  .idea/deploymentTargetDropDown.xml
  app/src/debug/res/drawable-xhdpi/message_incoming.xml
  app/src/debug/res/drawable-xhdpi/message_outgoing.xml
  app/src/main/java/com/example/starca/DetailFragment.kt
  app/src/main/java/com/example/starca/adapters/ChatAdapter.java
  app/src/main/java/com/example/starca/adapters/ConversationsAdapter.kt
  app/src/main/java/com/example/starca/fragments/ConversationsFragment.kt
  app/src/main/java/com/example/starca/fragments/MessagingFragment.kt
  app/src/main/java/com/example/starca/models/Message.kt
  app/src/main/res/drawable/ic_baseline_send_24.xml
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/message_incoming.xml
  app/src/main/res/layout/message_outgoing.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#61 Notify owners about requests
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/starca/ListingRequest.kt
  app/src/main/java/com/example/starca/adapters/ListingsGridAdapter.kt
  app/src/main/java/com/example/starca/adapters/RequestsAdapter.kt
  app/src/main/java/com/example/starca/fragments/OwnerListingDetailFragment.kt
  app/src/main/java/com/example/starca/models/Listing.kt
  app/src/main/res/layout/fragment_owner_listing_detail.xml
  app/src/main/res/layout/item_request.xml
Labels: Story

#62 Password Requirement Validation on Updating Password
  app/src/main/java/com/example/starca/fragments/EditPasswordFragment.kt
  app/src/main/res/layout/fragment_edit_password.xml
Labels: enhancement

#65 Fix listing request appearance issue
  app/src/main/java/com/example/starca/FileUtils.kt
  app/src/main/java/com/example/starca/SettingsActivity.kt
  app/src/main/java/com/example/starca/adapters/ListingsAdapter.kt
  app/src/main/java/com/example/starca/adapters/ListingsGridAdapter.kt
  app/src/main/java/com/example/starca/adapters/RequestsAdapter.kt
  app/src/main/java/com/example/starca/fragments/DashboardFragment.kt
  app/src/main/java/com/example/starca/fragments/DetailFragment.kt
  app/src/main/java/com/example/starca/fragments/OwnerListingDetailFragment.kt
  app/src/main/java/com/example/starca/models/Listing.kt
  app/src/main/java/com/example/starca/models/ListingRequest.kt
  app/src/main/res/drawable/ic_baseline_block_24.xml
  app/src/main/res/drawable/ic_baseline_check_circle_24.xml
  app/src/main/res/layout/fragment_owner_listing_detail.xml
  app/src/main/res/layout/item_request.xml
Labels: bug

#69 Filter out bought listings from requests page
  app/src/main/java/com/example/starca/fragments/OwnerListingDetailFragment.kt
  app/src/main/res/layout/item_request.xml
Labels: bug, enhancement

#70 Rented listings
  app/src/main/java/com/example/starca/adapters/ListingsGridAdapter.kt
  app/src/main/java/com/example/starca/adapters/ProfileViewPager2Adapter.kt
  app/src/main/java/com/example/starca/fragments/DetailFragment.kt
  app/src/main/java/com/example/starca/fragments/ListingsChildFragment.kt
  app/src/main/java/com/example/starca/fragments/ProfileFragment.kt
  app/src/main/java/com/example/starca/fragments/RentedChildFragment.kt
  app/src/main/res/layout/fragment_listings_child.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_rented_child.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, Story

#76 feat: Implemented live query
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/java/com/example/starca/fragments/MessagingFragment.kt
  gradle.properties
Labels: enhancement, Stretch

#77 Added rental fragment when clicking on a rental in profile page. Adde…
  README.md
  app/src/main/java/com/example/starca/adapters/ListingsGridAdapter.kt
  app/src/main/java/com/example/starca/fragments/DetailFragment.kt
  app/src/main/java/com/example/starca/fragments/RentalDetailFragment.kt
  app/src/main/java/com/example/starca/fragments/SignInFragment.kt
  app/src/main/java/com/example/starca/models/Listing.kt
  app/src/main/res/layout/fragment_rental_detail.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, Stretch

#79 Fixed a bug where user would not see the rental in their profile page…
  app/src/main/java/com/example/starca/fragments/DashboardFragment.kt
  app/src/main/java/com/example/starca/fragments/DetailFragment.kt
  app/src/main/java/com/example/starca/fragments/SignInFragment.kt
Labels: bug

#80 fixed a few bugs and implemented functionality for removing listing r…
  app/src/main/java/com/example/starca/fragments/DashboardFragment.kt
  app/src/main/java/com/example/starca/fragments/DetailFragment.kt
  app/src/main/java/com/example/starca/fragments/RentalDetailFragment.kt
Labels: bug, enhancement

#82 Create listing zip code bug
  app/src/main/java/com/example/starca/fragments/CreateListingDetailsFragment.kt
Labels: bug

#83 Account deleted remove all requests
  app/src/main/java/com/example/starca/SettingsActivity.kt
Labels: enhancement

#85 Edit listing
  app/src/debug/res/drawable-anydpi/ic_edit.xml
  app/src/debug/res/drawable-hdpi/ic_edit.png
  app/src/debug/res/drawable-mdpi/ic_edit.png
  app/src/debug/res/drawable-xhdpi/ic_edit.png
  app/src/debug/res/drawable-xxhdpi/ic_edit.png
  app/src/main/java/com/example/starca/adapters/ChatAdapter.java
  app/src/main/java/com/example/starca/adapters/ConversationsAdapter.kt
  app/src/main/java/com/example/starca/adapters/ListingsGridAdapter.kt
  app/src/main/java/com/example/starca/adapters/RequestsAdapter.kt
  app/src/main/java/com/example/starca/fragments/ConversationsFragment.kt
  app/src/main/java/com/example/starca/fragments/CreateListingDetailsFragment.kt
  app/src/main/java/com/example/starca/fragments/EditListingFragment.kt
  app/src/main/java/com/example/starca/fragments/MessagingFragment.kt
  app/src/main/java/com/example/starca/fragments/OwnerListingDetailFragment.kt
  app/src/main/java/com/example/starca/fragments/SignInFragment.kt
  app/src/main/res/drawable/ic_baseline_send_24.xml
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/fragment_edit_listing.xml
  app/src/main/res/layout/fragment_owner_listing_detail.xml
  app/src/main/res/layout/item_listing.xml
  app/src/main/res/layout/item_listing_gridview.xml
  app/src/main/res/layout/item_request.xml
  app/src/main/res/layout/message_incoming.xml
  app/src/main/res/layout/message_outgoing.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#91 Allow user to change listing image
  app/src/main/java/com/example/starca/fragments/EditListingFragment.kt
  app/src/main/res/layout/fragment_edit_listing.xml
Labels: enhancement

#93 Fix chat
  app/src/debug/res/drawable-anydpi/ic_dollar.xml
  app/src/debug/res/drawable-hdpi/ic_dollar.png
  app/src/debug/res/drawable-mdpi/ic_dollar.png
  app/src/debug/res/drawable-xhdpi/ic_dollar.png
  app/src/debug/res/drawable-xxhdpi/ic_dollar.png
  app/src/main/java/com/example/starca/fragments/ConversationsFragment.kt
  app/src/main/java/com/example/starca/fragments/CreateListingSubmitFragment.kt
  app/src/main/java/com/example/starca/fragments/DetailFragment.kt
  app/src/main/java/com/example/starca/fragments/MessagingFragment.kt
  app/src/main/java/com/example/starca/fragments/SignInFragment.kt
  app/src/main/res/layout/fragment_create_listing_details.xml
  app/src/main/res/layout/fragment_create_listing_image.xml
  app/src/main/res/layout/fragment_create_listing_submit.xml
  app/src/main/res/layout/fragment_rental_detail.xml
Labels: bug, enhancement
